version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
      - aws s3 rm s3://tnet-test-index --recursive
artifacts:
  base-directory: ./build
  files:
      - ./**/*

