version: 0.2

phases:
  build:
    commands:
      - cd ./public
      - npm
      - npm run build
      - aws s3 rm s3://pdftest-20200803 --recursive
artifacts:
  base-directory: ./build
  files:
      - ./**/*

